---

- hosts: prireg
  any_errors_fatal: true
  vars_files:
    - vars/data-dir.yaml
    - vars/prireg.yaml
  tasks:
    - import_tasks: tasks/destroy-prireg.yaml
      tags: ['prireg']

- hosts: nodes
  any_errors_fatal: true
  vars_files:
    - vars/ulimits.yaml
    - vars/ntp.yaml
    - vars/data-dir.yaml
    - vars/docker.yaml
    - vars/hosts.yaml
    - vars/prireg.yaml
    - vars/tools.yaml
  tasks:
#    - import_tasks: tasks/remove-ulimits.yaml
#      tags: ['ulimits']

    - import_tasks: tasks/remove-hosts.yaml
      tags: ['hosts']

    - import_tasks: tasks/disable-docker.yaml
      tags: ['docker']

    - import_tasks: tasks/destroy-data-dir.yaml
      tags: ['data-dir']

#    - import_tasks: tasks/disable-ntp.yaml
#      tags: ['ntp']
      
#    - import_tasks: tasks/enable-firewall.yaml
#      tags: ['firewall']
      
#    - import_tasks: tasks/remove-tools.yaml
#      tags: ['tools']
